spring.application.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/db_back
spring.datasource.username=root
spring.datasource.password=Lui$58408087
spring.datasource.driverClassName=com.mysql.jdbc.Driver


# carpeta de archivos
app.upload.dir=uploads